<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />

<meta name="author" content="Daniel Antal, based on the work of Jorg Beutel" />

<meta name="date" content="2021-12-18" />

<title>Introduction to iotables</title>

<script src="data:application/javascript;base64,Ly8gUGFuZG9jIDIuOSBhZGRzIGF0dHJpYnV0ZXMgb24gYm90aCBoZWFkZXIgYW5kIGRpdi4gV2UgcmVtb3ZlIHRoZSBmb3JtZXIgKHRvCi8vIGJlIGNvbXBhdGlibGUgd2l0aCB0aGUgYmVoYXZpb3Igb2YgUGFuZG9jIDwgMi44KS4KZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcignRE9NQ29udGVudExvYWRlZCcsIGZ1bmN0aW9uKGUpIHsKICB2YXIgaHMgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yQWxsKCJkaXYuc2VjdGlvbltjbGFzcyo9J2xldmVsJ10gPiA6Zmlyc3QtY2hpbGQiKTsKICB2YXIgaSwgaCwgYTsKICBmb3IgKGkgPSAwOyBpIDwgaHMubGVuZ3RoOyBpKyspIHsKICAgIGggPSBoc1tpXTsKICAgIGlmICghL15oWzEtNl0kL2kudGVzdChoLnRhZ05hbWUpKSBjb250aW51ZTsgIC8vIGl0IHNob3VsZCBiZSBhIGhlYWRlciBoMS1oNgogICAgYSA9IGguYXR0cmlidXRlczsKICAgIHdoaWxlIChhLmxlbmd0aCA+IDApIGgucmVtb3ZlQXR0cmlidXRlKGFbMF0ubmFtZSk7CiAgfQp9KTsK"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="data:text/css,body%20%7B%0Abackground%2Dcolor%3A%20%23fff%3B%0Amargin%3A%201em%20auto%3B%0Amax%2Dwidth%3A%20700px%3B%0Aoverflow%3A%20visible%3B%0Apadding%2Dleft%3A%202em%3B%0Apadding%2Dright%3A%202em%3B%0Afont%2Dfamily%3A%20%22Open%20Sans%22%2C%20%22Helvetica%20Neue%22%2C%20Helvetica%2C%20Arial%2C%20sans%2Dserif%3B%0Afont%2Dsize%3A%2014px%3B%0Aline%2Dheight%3A%201%2E35%3B%0A%7D%0A%23TOC%20%7B%0Aclear%3A%20both%3B%0Amargin%3A%200%200%2010px%2010px%3B%0Apadding%3A%204px%3B%0Awidth%3A%20400px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Aborder%2Dradius%3A%205px%3B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Afont%2Dsize%3A%2013px%3B%0Aline%2Dheight%3A%201%2E3%3B%0A%7D%0A%23TOC%20%2Etoctitle%20%7B%0Afont%2Dweight%3A%20bold%3B%0Afont%2Dsize%3A%2015px%3B%0Amargin%2Dleft%3A%205px%3B%0A%7D%0A%23TOC%20ul%20%7B%0Apadding%2Dleft%3A%2040px%3B%0Amargin%2Dleft%3A%20%2D1%2E5em%3B%0Amargin%2Dtop%3A%205px%3B%0Amargin%2Dbottom%3A%205px%3B%0A%7D%0A%23TOC%20ul%20ul%20%7B%0Amargin%2Dleft%3A%20%2D2em%3B%0A%7D%0A%23TOC%20li%20%7B%0Aline%2Dheight%3A%2016px%3B%0A%7D%0Atable%20%7B%0Amargin%3A%201em%20auto%3B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dcolor%3A%20%23DDDDDD%3B%0Aborder%2Dstyle%3A%20outset%3B%0Aborder%2Dcollapse%3A%20collapse%3B%0A%7D%0Atable%20th%20%7B%0Aborder%2Dwidth%3A%202px%3B%0Apadding%3A%205px%3B%0Aborder%2Dstyle%3A%20inset%3B%0A%7D%0Atable%20td%20%7B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dstyle%3A%20inset%3B%0Aline%2Dheight%3A%2018px%3B%0Apadding%3A%205px%205px%3B%0A%7D%0Atable%2C%20table%20th%2C%20table%20td%20%7B%0Aborder%2Dleft%2Dstyle%3A%20none%3B%0Aborder%2Dright%2Dstyle%3A%20none%3B%0A%7D%0Atable%20thead%2C%20table%20tr%2Eeven%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Ap%20%7B%0Amargin%3A%200%2E5em%200%3B%0A%7D%0Ablockquote%20%7B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Apadding%3A%200%2E25em%200%2E75em%3B%0A%7D%0Ahr%20%7B%0Aborder%2Dstyle%3A%20solid%3B%0Aborder%3A%20none%3B%0Aborder%2Dtop%3A%201px%20solid%20%23777%3B%0Amargin%3A%2028px%200%3B%0A%7D%0Adl%20%7B%0Amargin%2Dleft%3A%200%3B%0A%7D%0Adl%20dd%20%7B%0Amargin%2Dbottom%3A%2013px%3B%0Amargin%2Dleft%3A%2013px%3B%0A%7D%0Adl%20dt%20%7B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0Aul%20%7B%0Amargin%2Dtop%3A%200%3B%0A%7D%0Aul%20li%20%7B%0Alist%2Dstyle%3A%20circle%20outside%3B%0A%7D%0Aul%20ul%20%7B%0Amargin%2Dbottom%3A%200%3B%0A%7D%0Apre%2C%20code%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0Aborder%2Dradius%3A%203px%3B%0Acolor%3A%20%23333%3B%0Awhite%2Dspace%3A%20pre%2Dwrap%3B%20%0A%7D%0Apre%20%7B%0Aborder%2Dradius%3A%203px%3B%0Amargin%3A%205px%200px%2010px%200px%3B%0Apadding%3A%2010px%3B%0A%7D%0Apre%3Anot%28%5Bclass%5D%29%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Acode%20%7B%0Afont%2Dfamily%3A%20Consolas%2C%20Monaco%2C%20%27Courier%20New%27%2C%20monospace%3B%0Afont%2Dsize%3A%2085%25%3B%0A%7D%0Ap%20%3E%20code%2C%20li%20%3E%20code%20%7B%0Apadding%3A%202px%200px%3B%0A%7D%0Adiv%2Efigure%20%7B%0Atext%2Dalign%3A%20center%3B%0A%7D%0Aimg%20%7B%0Abackground%2Dcolor%3A%20%23FFFFFF%3B%0Apadding%3A%202px%3B%0Aborder%3A%201px%20solid%20%23DDDDDD%3B%0Aborder%2Dradius%3A%203px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Amargin%3A%200%205px%3B%0A%7D%0Ah1%20%7B%0Amargin%2Dtop%3A%200%3B%0Afont%2Dsize%3A%2035px%3B%0Aline%2Dheight%3A%2040px%3B%0A%7D%0Ah2%20%7B%0Aborder%2Dbottom%3A%204px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Apadding%2Dbottom%3A%202px%3B%0Afont%2Dsize%3A%20145%25%3B%0A%7D%0Ah3%20%7B%0Aborder%2Dbottom%3A%202px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Afont%2Dsize%3A%20120%25%3B%0A%7D%0Ah4%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23f7f7f7%3B%0Amargin%2Dleft%3A%208px%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Ah5%2C%20h6%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23ccc%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Aa%20%7B%0Acolor%3A%20%230033dd%3B%0Atext%2Ddecoration%3A%20none%3B%0A%7D%0Aa%3Ahover%20%7B%0Acolor%3A%20%236666ff%3B%20%7D%0Aa%3Avisited%20%7B%0Acolor%3A%20%23800080%3B%20%7D%0Aa%3Avisited%3Ahover%20%7B%0Acolor%3A%20%23BB00BB%3B%20%7D%0Aa%5Bhref%5E%3D%22http%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0Aa%5Bhref%5E%3D%22https%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0A%0Acode%20%3E%20span%2Ekw%20%7B%20color%3A%20%23555%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Edt%20%7B%20color%3A%20%23902000%3B%20%7D%20%0Acode%20%3E%20span%2Edv%20%7B%20color%3A%20%2340a070%3B%20%7D%20%0Acode%20%3E%20span%2Ebn%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Efl%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Ech%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Est%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Eco%20%7B%20color%3A%20%23888888%3B%20font%2Dstyle%3A%20italic%3B%20%7D%20%0Acode%20%3E%20span%2Eot%20%7B%20color%3A%20%23007020%3B%20%7D%20%0Acode%20%3E%20span%2Eal%20%7B%20color%3A%20%23ff0000%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Efu%20%7B%20color%3A%20%23900%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Eer%20%7B%20color%3A%20%23a61717%3B%20background%2Dcolor%3A%20%23e3d2d2%3B%20%7D%20%0A" type="text/css" />




</head>

<body>




<h1 class="title toc-ignore">Introduction to iotables</h1>
<h4 class="author">Daniel Antal, based on the work of Jorg Beutel</h4>
<h4 class="date">2021-12-18</h4>



<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(iotables)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr, <span class="at">quietly =</span> T)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr, <span class="at">quietly =</span> T)</span></code></pre></div>
<p>This introduction shows the reproducible workflow of iotables with the examples of the <a href="https://ec.europa.eu/eurostat/documents/3859598/5902113/KS-RA-07-013-EN.PDF/b0b3d71e-3930-4442-94be-70b36cea9b39?version=1.0">Eurostat Manual of Supply, Use and Input-Output Tables</a>. by Joerg Beutel (Eurostat Manual).</p>
<div id="germany-sample-files" class="section level2">
<h2>Germany sample files</h2>
<p>The <code>germany_1990</code> dataset is a simplified 6x6 sized SIOT taken from the <em>Eurostat Manual</em> (page 481). It is brought to a long form similar to the Eurostat bulk files. The testthat infrastructure of the iotables package is checking data processing functions and analytical calculations against these published results.</p>
<p>The following data processing functions select and order the data from the Eurostat-type bulk file. Since the first version of this package, Eurostat moved all SIOT data products to the ESA2010 vocabulary, but the manual still follows the ESA95 vocabulary. The labels of the dataset were slightly changed to match the current metadata names. The changes are minor and self-evident, the comparison of the <code>germany_1990</code> dataset and the Manual should cause no misunderstandings.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>germany_io <span class="ot">&lt;-</span> <span class="fu">iotable_get</span>( <span class="at">labelling =</span> <span class="st">&quot;iotables&quot;</span> )</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>input_flow <span class="ot">&lt;-</span> <span class="fu">input_flow_get</span> ( </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data_table =</span> germany_io, </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">households =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>de_output <span class="ot">&lt;-</span> <span class="fu">primary_input_get</span> ( germany_io, <span class="st">&quot;output&quot;</span> )</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span> (de_output[<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)])</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    iotables_row agriculture_group industry_group construction</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 15       output             43910        1079446       245606</span></span></code></pre></div>
<p>This vignette uses <code>library(tidyverse)</code>, more particularly <code>dplyr</code> and <code>tidyr</code>, just like all analytical functions of <code>iotables</code>. Even if you do not use <code>tidyverse</code>, this packages will be installed together with <code>iotables</code>. These functions are only used in the vignette to print the output, and they are not essential for the examples.</p>
</div>
<div id="direct-effects" class="section level2">
<h2>Direct effects</h2>
<p>The input coefficient matrix shows what happens in the whole domestic economy when an industry is facing additional demand, increases production. In the Germany example, all results are rounded to 4 digits for easier comparison with the Eurostat manual.</p>
<blockquote>
<p>The input coefficients for domestic intermediates are defined on page 486. You can check the following results against Table 15.8 of the Eurostat manual. (Only the top-right corner of the resulting input coefficient matrix is printed for readability.)</p>
</blockquote>
<p>The <code>input_coefficient_matrix_create()</code> function relies on the following equation. The numbering of the equations is the numbering of the Eurostat Manual.</p>
<ol start="9" style="list-style-type: decimal">
<li> =  [recap: (43) is the same]</li>
</ol>
<p>It checks the correct ordering of columns, and furthermore it fills up 0 values with 0.000001 to avoid division with zero.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>de_input_coeff <span class="ot">&lt;-</span> <span class="fu">input_coefficient_matrix_create</span>( </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">data_table =</span> germany_io, </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">digits =</span> <span class="dv">4</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="do">## which is equivalent to:</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>de_input_coeff <span class="ot">&lt;-</span> <span class="fu">coefficient_matrix_create</span>( </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data_table =</span> germany_io, </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">total =</span> <span class="st">&quot;output&quot;</span>, </span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">return_part =</span> <span class="st">&quot;products&quot;</span>, </span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">households =</span> <span class="cn">FALSE</span>,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">4</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span> ( de_input_coeff[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;        iotables_row agriculture_group industry_group</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1 agriculture_group            0.0258         0.0236</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2    industry_group            0.1806         0.2822</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3      construction            0.0097         0.0068</span></span></code></pre></div>
<p>Similarly, the output coefficient matrix is the following:</p>
<pre><code>#&gt;        iotables_row agriculture_group industry_group
#&gt; 1 agriculture_group            0.0258         0.5803
#&gt; 2    industry_group            0.0073         0.2822
#&gt; 3      construction            0.0017         0.0299</code></pre>
<p>These results can be checked on page 468 in the Manual.</p>
<p>The Leontieff matrix is derived from Leontieff equation system.</p>
<ol start="19" style="list-style-type: decimal">
<li></li>
</ol>
<p>The Leontieff matrix is defined as  and it is created with the <code>leontieff_matrix_create()</code> function.</p>
<p>The Leontieff inverse is  and it is created with the <code>leontieff_inverse_create()</code> function from the Leontieff-matrix.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>L_de <span class="ot">&lt;-</span> <span class="fu">leontieff_matrix_create</span> ( </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">technology_coefficients_matrix =</span> de_input_coeff </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>I_de <span class="ot">&lt;-</span> <span class="fu">leontieff_inverse_create</span>(de_input_coeff)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>I_de_4 <span class="ot">&lt;-</span> <span class="fu">leontieff_inverse_create</span>(de_input_coeff, <span class="at">digits =</span> <span class="dv">4</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span> (I_de_4[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;              iotables_row agriculture_group industry_group</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1          industry_group            1.4155         0.5605</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2            construction            0.0441         1.0462</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3             trade_group            0.2180         0.2292</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4 business_services_group            0.2892         0.3237</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5    other_services_group            0.1089         0.1014</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6                   total            1.1152         1.3025</span></span></code></pre></div>
<blockquote>
<p>You can check the Leontieff matrix against Table 15.9 on page 487 of the Eurostat manual, and the Leontieff inverse against Table 15.10 on page 488. The ordering of the industries is different in the manual.</p>
</blockquote>
</div>
<div id="creating-indicators" class="section level2">
<h2>Creating indicators</h2>
<div id="creating-technical-indicators" class="section level3">
<h3>Creating technical indicators</h3>
<p>Technical indicators assume constant returns to scale and fixed relationship of all inputs to each industry. With these conditions the technical input coefficients show how much input products, labour or capital is required to produce a unit of industry output.</p>
<ol start="60" style="list-style-type: decimal">
<li><span class="math inline">\(a_{ij}\)</span> = <span class="math inline">\(z_{ij}\)</span> / <span class="math inline">\(x_j\)</span> [technical input coefficients]</li>
</ol>
<p>The helper function <code>primary_input_get()</code> selects a row from the SIOT and brings it to a conforming form. The <code>input_indicator_create()</code> creates the vector of technical input coefficients.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>de_emp <span class="ot">&lt;-</span> <span class="fu">primary_input_get</span> ( germany_io,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">primary_input =</span> <span class="st">&quot;employment_domestic_total&quot;</span> )</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>de_emp_indicator <span class="ot">&lt;-</span> <span class="fu">input_indicator_create</span> ( </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">data_table  =</span> germany_io,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">input_vector =</span> <span class="st">&quot;employment_domestic_total&quot;</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span> ( tidyr<span class="sc">::</span><span class="fu">gather</span>( de_emp_indicator, indicators, values, <span class="sc">!!</span><span class="dv">2</span><span class="sc">:</span><span class="fu">ncol</span>(de_emp_indicator))[,<span class="sc">-</span><span class="dv">1</span>] )</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                indicators      values</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1       agriculture_group 0.024960146</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2          industry_group 0.007764168</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3            construction 0.013175574</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4             trade_group 0.017129483</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5 business_services_group 0.006148852</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6    other_services_group 0.020054311</span></span></code></pre></div>
<p>Often we want to analyze the effect of growing domestic demand on some natural units, such as employment or <span class="math inline">\(CO_2\)</span> emissions. The only difficulty is that we need data that is aggregated / disaggregated precisely with the same industry breakup as our SIOT table.</p>
<p>European employment statistics have greater detail than our tables, so employment statistics must be aggregated to conform the 60 (61, 62) columns of the SIOT. There is a difference in the columns based on how national statistics offices treat imputed real estate income and household production, and trade margins. Czech SIOTs are smaller than most SIOTs because they do not have these columns and rows.</p>
<p>In another vignette we will show examples on how to work with these real-life data. For the sake of following the calculations, we are continuing with the simplified 1990 German data.</p>
</div>
<div id="creating-income-indicators" class="section level3">
<h3>Creating income indicators</h3>
<p>The input coefficients for value added are created with <code>input_indicator_create()</code>.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>de_gva <span class="ot">&lt;-</span> <span class="fu">primary_input_get</span> ( germany_io,</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">primary_input =</span> <span class="st">&quot;gva&quot;</span>) </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>de_gva_indicator  <span class="ot">&lt;-</span> <span class="fu">input_indicator_create</span>( </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">data_table  =</span> germany_io,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">input_vector =</span> <span class="st">&quot;gva&quot;</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>( tidyr<span class="sc">::</span><span class="fu">gather</span>(de_gva_indicator, indicators, values,<span class="sc">!!</span><span class="dv">2</span><span class="sc">:</span><span class="fu">ncol</span>(de_gva_indicator))[,<span class="sc">-</span><span class="dv">1</span>]  ) </span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                indicators    values</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1       agriculture_group 0.4933728</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2          industry_group 0.3659488</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3            construction 0.4707703</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4             trade_group 0.5766124</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5 business_services_group 0.5999044</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6    other_services_group 0.7172413</span></span></code></pre></div>
<p>This is equal to the equation on page 495 of the Eurostat Manual. The results above can be checked on the bottom of page 498.</p>
<ol start="44" style="list-style-type: decimal">
<li><span class="math inline">\(w_{ij}\)</span> = <span class="math inline">\(W_{j}\)</span> / <span class="math inline">\(x_j\)</span> [input coefficients for value added]</li>
</ol>
<p>You can create a matrix of input indicators, or direct effects on (final) demand with <code>direct_supply_effects_create()</code>. The function by default creates input requirements for final demand. With the code below it re-creates the Table 15.14 of the Eurostat manual.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>direct_effects_de <span class="ot">&lt;-</span> <span class="fu">coefficient_matrix_create</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data_table  =</span> germany_io, </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">total       =</span> <span class="st">&#39;output&#39;</span>, </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">return_part =</span> <span class="st">&#39;primary_inputs&#39;</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span> ( direct_effects_de[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>])</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
iotables_row
</th>
<th style="text-align:right;">
agriculture_group
</th>
<th style="text-align:right;">
industry_group
</th>
<th style="text-align:right;">
construction
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
7
</td>
<td style="text-align:left;">
total
</td>
<td style="text-align:right;">
0.4152813
</td>
<td style="text-align:right;">
0.4828551
</td>
<td style="text-align:right;">
0.4682581
</td>
</tr>
<tr>
<td style="text-align:left;">
8
</td>
<td style="text-align:left;">
imports
</td>
<td style="text-align:right;">
0.0666591
</td>
<td style="text-align:right;">
0.1451698
</td>
<td style="text-align:right;">
0.0546689
</td>
</tr>
<tr>
<td style="text-align:left;">
9
</td>
<td style="text-align:left;">
intermediate_consumption
</td>
<td style="text-align:right;">
0.5066272
</td>
<td style="text-align:right;">
0.6340512
</td>
<td style="text-align:right;">
0.5292297
</td>
</tr>
<tr>
<td style="text-align:left;">
10
</td>
<td style="text-align:left;">
compensation_employees
</td>
<td style="text-align:right;">
0.2136643
</td>
<td style="text-align:right;">
0.2746446
</td>
<td style="text-align:right;">
0.3209164
</td>
</tr>
<tr>
<td style="text-align:left;">
11
</td>
<td style="text-align:left;">
net_tax_production
</td>
<td style="text-align:right;">
-0.0458210
</td>
<td style="text-align:right;">
0.0013498
</td>
<td style="text-align:right;">
0.0039209
</td>
</tr>
<tr>
<td style="text-align:left;">
12
</td>
<td style="text-align:left;">
consumption_fixed_capital
</td>
<td style="text-align:right;">
0.1792530
</td>
<td style="text-align:right;">
0.0590757
</td>
<td style="text-align:right;">
0.0238594
</td>
</tr>
</tbody>
</table>
<blockquote>
<p>The ‘total’ row above is labelled as Domestic goods and services in the Eurostat Manual. The table can be found on p498.</p>
</blockquote>
</div>
</div>
<div id="multipliers" class="section level2">
<h2>Multipliers</h2>
<div id="income-multipliers" class="section level3">
<h3>Income multipliers</h3>
<p>The SIOTs contain (with various breakups) three types of income:</p>
<ul>
<li><p>Employee wages, which is usually a proxy for all household income.</p></li>
<li><p>Gross operating surplus, which is a form of corporate sector income.</p></li>
<li><p>Taxes that are the income of government.</p></li>
</ul>
<p>These together make gross value added (GVA). If you are working with SIOTs that use basic prices, then GVA = GDP at producers’ prices, or basic prices.</p>
<p>The GVA multiplier shows the additional gross value created in the economy if demand for the industry products is growing with unity. The wage multiplier (not shown here) shows the increase in household income.</p>
<p>The following equation is used to work with different income effects and multipliers:</p>
<ol start="63" style="list-style-type: decimal">
<li>Z = B(I-A)<sup>-1</sup></li>
</ol>
<p>B = vector of input coefficients for wages or GVA or taxes.</p>
<p>Z = direct and indirect requirements for wages (or other income)</p>
<p>The indicator shows that manufacturing has the lowest, and other services has the highest gross value added component. This is hardly surprising, because manufacturing needs a lot of materials and imported components. When the demand for manufacturing in the domestic economy is growing by 1 unit, the gross value added is 0.3659488.</p>
<blockquote>
<p>You can check these values against the Table 15.16 of the Eurostat Manual on page 501 (row 10).</p>
</blockquote>
<p>You can recreate the whole matrix, when the data data permits, with <code>input_multipliers_create()</code> as shown here. Alternatively, you can create your own custom multipliers with <code>multiplier_create()</code> as shown in the following example.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>input_reqr <span class="ot">&lt;-</span> <span class="fu">coefficient_matrix_create</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">data_table  =</span> <span class="fu">iotable_get</span> (), </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">total       =</span> <span class="st">&#39;output&#39;</span>, </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">return_part =</span> <span class="st">&#39;primary_inputs&#39;</span>) </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>multipliers <span class="ot">&lt;-</span> <span class="fu">input_multipliers_create</span>(</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">input_requirements =</span> input_reqr,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">inverse =</span> I_de)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(multipliers, <span class="at">digits=</span> <span class="dv">4</span>)</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
agriculture_group
</th>
<th style="text-align:left;">
industry_group
</th>
<th style="text-align:left;">
construction
</th>
<th style="text-align:left;">
trade_group
</th>
<th style="text-align:left;">
business_services_group
</th>
<th style="text-align:left;">
other_services_group
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
7
</td>
<td style="text-align:left;">
&lt;environment&gt;_multiplier
</td>
<td style="text-align:left;">
2.68540535089593
</td>
<td style="text-align:left;">
2.69747311050155
</td>
<td style="text-align:left;">
2.74636047622115
</td>
<td style="text-align:left;">
2.77371865536628
</td>
<td style="text-align:left;">
2.68772796636426
</td>
<td style="text-align:left;">
2.73334099836677
</td>
</tr>
<tr>
<td style="text-align:left;">
8
</td>
<td style="text-align:left;">
&lt;environment&gt;_multiplier
</td>
<td style="text-align:left;">
2.35081996257473
</td>
<td style="text-align:left;">
1.73682349074383
</td>
<td style="text-align:left;">
2.9606273455949
</td>
<td style="text-align:left;">
3.0302277674519
</td>
<td style="text-align:left;">
5.09751098391137
</td>
<td style="text-align:left;">
2.89208896375524
</td>
</tr>
<tr>
<td style="text-align:left;">
9
</td>
<td style="text-align:left;">
&lt;environment&gt;_multiplier
</td>
<td style="text-align:left;">
2.64848127175063
</td>
<td style="text-align:left;">
2.54644792085702
</td>
<td style="text-align:left;">
2.84866699311511
</td>
<td style="text-align:left;">
2.82882102073116
</td>
<td style="text-align:left;">
2.85049778465738
</td>
<td style="text-align:left;">
2.68656726640444
</td>
</tr>
<tr>
<td style="text-align:left;">
10
</td>
<td style="text-align:left;">
&lt;environment&gt;_multiplier
</td>
<td style="text-align:left;">
5.22850448128565
</td>
<td style="text-align:left;">
4.82854808114035
</td>
<td style="text-align:left;">
4.27486775886289
</td>
<td style="text-align:left;">
3.13476810284758
</td>
<td style="text-align:left;">
5.68434652746025
</td>
<td style="text-align:left;">
1.96790238232353
</td>
</tr>
<tr>
<td style="text-align:left;">
11
</td>
<td style="text-align:left;">
&lt;environment&gt;_multiplier
</td>
<td style="text-align:left;">
1.75440922457173
</td>
<td style="text-align:left;">
-31.7613134068736
</td>
<td style="text-align:left;">
-9.91411023641964
</td>
<td style="text-align:left;">
-4.38676650006166
</td>
<td style="text-align:left;">
-1.6240518561975
</td>
<td style="text-align:left;">
2.01445864325335
</td>
</tr>
<tr>
<td style="text-align:left;">
12
</td>
<td style="text-align:left;">
&lt;environment&gt;_multiplier
</td>
<td style="text-align:left;">
2.27053561307396
</td>
<td style="text-align:left;">
5.6352096656793
</td>
<td style="text-align:left;">
12.3233231138882
</td>
<td style="text-align:left;">
3.58912866300644
</td>
<td style="text-align:left;">
2.32532653122482
</td>
<td style="text-align:left;">
2.31013210744462
</td>
</tr>
<tr>
<td style="text-align:left;">
13
</td>
<td style="text-align:left;">
&lt;environment&gt;_multiplier
</td>
<td style="text-align:left;">
2.77095806176288
</td>
<td style="text-align:left;">
10.7799950860823
</td>
<td style="text-align:left;">
3.44055299146446
</td>
<td style="text-align:left;">
3.38397950563377
</td>
<td style="text-align:left;">
1.82021802278639
</td>
<td style="text-align:left;">
2.47400125492644
</td>
</tr>
<tr>
<td style="text-align:left;">
14
</td>
<td style="text-align:left;">
&lt;environment&gt;_multiplier
</td>
<td style="text-align:left;">
3.74784006299814
</td>
<td style="text-align:left;">
5.32599431442647
</td>
<td style="text-align:left;">
4.34825682354541
</td>
<td style="text-align:left;">
3.17086366371906
</td>
<td style="text-align:left;">
3.05175143664354
</td>
<td style="text-align:left;">
2.08423434432194
</td>
</tr>
<tr>
<td style="text-align:left;">
15
</td>
<td style="text-align:left;">
&lt;environment&gt;_multiplier
</td>
<td style="text-align:left;">
3.19087500560593
</td>
<td style="text-align:left;">
3.56361966958793
</td>
<td style="text-align:left;">
3.55462928456431
</td>
<td style="text-align:left;">
3.02604703570521
</td>
<td style="text-align:left;">
2.97123073651063
</td>
<td style="text-align:left;">
2.25454922770314
</td>
</tr>
<tr>
<td style="text-align:left;">
16
</td>
<td style="text-align:left;">
&lt;environment&gt;_multiplier
</td>
<td style="text-align:left;">
2.83108650121869
</td>
<td style="text-align:left;">
9.9490354421885
</td>
<td style="text-align:left;">
9.47830131848828
</td>
<td style="text-align:left;">
3.60865781075941
</td>
<td style="text-align:left;">
4.20737388852734
</td>
<td style="text-align:left;">
2.02287459868216
</td>
</tr>
<tr>
<td style="text-align:left;">
17
</td>
<td style="text-align:left;">
&lt;environment&gt;_multiplier
</td>
<td style="text-align:left;">
4.0230603476267
</td>
<td style="text-align:left;">
6.23914984017754
</td>
<td style="text-align:left;">
4.2992398416755
</td>
<td style="text-align:left;">
3.09627453198874
</td>
<td style="text-align:left;">
6.79232294779834
</td>
<td style="text-align:left;">
2.0068221758786
</td>
</tr>
<tr>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
&lt;environment&gt;_multiplier
</td>
<td style="text-align:left;">
1.59601249923798
</td>
<td style="text-align:left;">
34.0196753138538
</td>
<td style="text-align:left;">
8.51898255772015
</td>
<td style="text-align:left;">
3.82271704696259
</td>
<td style="text-align:left;">
7.41331274154061
</td>
<td style="text-align:left;">
4.25079330153506
</td>
</tr>
<tr>
<td style="text-align:left;">
19
</td>
<td style="text-align:left;">
&lt;environment&gt;_multiplier
</td>
<td style="text-align:left;">
2.66559654191294
</td>
<td style="text-align:left;">
7.39598117179823
</td>
<td style="text-align:left;">
4.7425997067729
</td>
<td style="text-align:left;">
3.19631644789801
</td>
<td style="text-align:left;">
6.88055658453251
</td>
<td style="text-align:left;">
2.14995613656862
</td>
</tr>
</tbody>
</table>
<blockquote>
<p>You can check these results against the Table 15.16 on p501 of the Eurostat manual. the label ‘total’ refers to domestic intermediaries. The ordering of the rows is different from the Manual.</p>
</blockquote>
<p>These multipliers are Type-I multipliers. The type-I GVA multiplier shows the total effect in the domestic economy. The initial extra demand creates new orders in the backward linking industries, offers new product to build on in the forward-linking industry and creates new corporate and employee income that can be spent. Type-II multipliers will be introduced in a forthcoming vignette [not yet available.]</p>
</div>
<div id="employment-multipliers" class="section level3">
<h3>Employment multipliers</h3>
<p>The E matrix contains the input coefficients for labor (created by <code>input_indicator_create()</code>). The following matrix equation defines the employment multipliers.</p>
<ol start="64" style="list-style-type: decimal">
<li>Z = E(I-A)<sup>-1</sup></li>
</ol>
<p>The <code>multiplier_create()</code> function performs the matrix multiplication, after handling many exceptions and problems with real-life data, such as different missing columns and rows in the national variations of the standard European table.</p>
<p>Please send a bug report on <a href="https://github.com/rOpenGov/iotables/issues">Github</a> if you run into further real-life problems.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>de_emp_indicator <span class="ot">&lt;-</span> <span class="fu">input_indicator_create</span> (</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data_table =</span> germany_io, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">input =</span> <span class="st">&#39;employment_domestic_total&#39;</span>) </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>employment_multipliers <span class="ot">&lt;-</span> <span class="fu">multiplier_create</span> ( </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">input_vector    =</span> de_emp_indicator,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Im              =</span> I_de,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">multiplier_name =</span> <span class="st">&quot;employment_multiplier&quot;</span>, </span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">4</span> )</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span> (tidyr<span class="sc">::</span><span class="fu">gather</span>(employment_multipliers,</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>              multipliers, values, </span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>              <span class="sc">!!</span><span class="dv">2</span><span class="sc">:</span><span class="fu">ncol</span>(employment_multipliers))[<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;               multipliers values</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1       agriculture_group 0.0665</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2          industry_group 0.0574</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3            construction 0.0625</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4             trade_group 0.0548</span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5 business_services_group 0.0423</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6    other_services_group 0.0431</span></span></code></pre></div>
<p>You can check against page 501 that these values are correct and on page 501 that the highest employment multiplier is indeed <span class="math inline">\(z_i\)</span> = 0.0665, the employment multiplier of agriculture.</p>
<p>For working with real-life, current employment data, there is a helper function to retrieve and process Eurostat employment statistics to a SIOT-conforming vector <code>employment_get()</code>. This function will be explained in a separate vignette.</p>
</div>
<div id="output-multipliers" class="section level3">
<h3>Output multipliers</h3>
<p><code>Output multipliers</code> and <code>forward linkages</code> are calculated with the help of output coefficients for product as defined on p486 and p495 of the the Eurostat Manual. The Eurostat Manual uses the definition of <em>output at basic prices</em> to define output coefficients which is no longer part of SNA as of SNA2010.</p>
<ol start="5" style="list-style-type: decimal">
<li><span class="math inline">\(b_{ij}\)</span> = <span class="math inline">\(X_{ij}\)</span> / <span class="math inline">\(x_i\)</span> [also (45) output coefficients for products / intermediates].</li>
</ol>
<p><span class="math inline">\(x_i\)</span>: output of sector i</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>de_input_coeff <span class="ot">&lt;-</span> <span class="fu">input_coefficient_matrix_create</span>( </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data_table =</span> <span class="fu">iotable_get</span>(), </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">digits =</span> <span class="dv">4</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>                           </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>output_multipliers <span class="ot">&lt;-</span> <span class="fu">output_multiplier_create</span> ( </span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>                        <span class="at">input_coefficient_matrix =</span> de_input_coeff )</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span> (</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">gather</span>(output_multipliers, multipliers, values)[<span class="sc">-</span><span class="dv">1</span>,]</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
multipliers
</th>
<th style="text-align:left;">
values
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
agriculture_group
</td>
<td style="text-align:left;">
1.70492243301356
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
industry_group
</td>
<td style="text-align:left;">
1.8414208680286
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
construction
</td>
<td style="text-align:left;">
1.81374666684297
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
trade_group
</td>
<td style="text-align:left;">
1.60371174683177
</td>
</tr>
<tr>
<td style="text-align:left;">
6
</td>
<td style="text-align:left;">
business_services_group
</td>
<td style="text-align:left;">
1.59497385374824
</td>
</tr>
<tr>
<td style="text-align:left;">
7
</td>
<td style="text-align:left;">
other_services_group
</td>
<td style="text-align:left;">
1.37837464728208
</td>
</tr>
</tbody>
</table>
<p>These multipliers can be checked against the Table 15.15 on p500 of the Eurostat Manual.</p>
</div>
</div>
<div id="interindustrial-linkage-analysis" class="section level2">
<h2>Interindustrial linkage analysis</h2>
<p>The <code>backward linkages</code>, i.e. demand side linkages, show how much incremental demand is created via suppliers when an industry is facing increased demand and produces more.</p>
<p><code>Forward linkages</code> on the other hand show the effect of increased production, which gives either more or cheaper supplies for other industries that rely on the output of the given industry.</p>
<p>For example, when a new concert is put on stage, orders are filled for real estate, security services, catering, etc, which show in the backward linkages. The concert attracts visitors that creates new opportunities for the hotel industry in forward linkages.</p>
<div id="backward-linkages" class="section level3">
<h3>Backward linkages</h3>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>de_coeff <span class="ot">&lt;-</span> <span class="fu">input_coefficient_matrix_create</span>( <span class="fu">iotable_get</span>(), <span class="at">digits =</span> <span class="dv">4</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>I_de <span class="ot">&lt;-</span> <span class="fu">leontieff_inverse_create</span> ( de_coeff )</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>de_bw <span class="ot">&lt;-</span> <span class="fu">backward_linkages</span>(I_de)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span> (tidyr<span class="sc">::</span><span class="fu">gather</span>(de_bw, backward_linkages, values)[<span class="sc">-</span><span class="dv">1</span>,])</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;         backward_linkages           values</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2       agriculture_group 1.70492243301356</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3          industry_group  1.8414208680286</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4            construction 1.81374666684297</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5             trade_group 1.60371174683177</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6 business_services_group 1.59497385374824</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7    other_services_group 1.37837464728208</span></span></code></pre></div>
<blockquote>
<p>You can check the results against Table 15.19 on page 506 of the Eurostat Manual.</p>
</blockquote>
<p>Manufacturing has the highest backward linkages, and other services the least. An increased demand for manufacturing usually effects supplier industries. Service industry usually have a high labor input, and their main effect is increased spending of the wages earned in the services.</p>
</div>
<div id="forward-linkages" class="section level3">
<h3>Forward linkages</h3>
<p>Forward linkages show the strength of the new business opportunities when industry i starts to increase its production. Whereas backward linkages show the increased demand of the suppliers in industry i, forward linkages show the increased availability of inputs for other industries that rely on industry i as a supplier.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>de_out <span class="ot">&lt;-</span> <span class="fu">output_coefficient_matrix_create</span> ( </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  germany_io, <span class="st">&quot;final_demand&quot;</span>, <span class="at">digits =</span> <span class="dv">4</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                                    </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">forward_linkages</span> ( <span class="at">output_coefficient_matrix =</span> de_out )</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;              iotables_row forward_linkages</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1       agriculture_group         2.112754</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2          industry_group         1.690891</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3            construction         1.355896</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4             trade_group         1.584989</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5 business_services_group         2.104036</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6    other_services_group         1.210504</span></span></code></pre></div>
<blockquote>
<p>You can check forward linkages against the Table 15.20 of Eurostat Manual on page 507.</p>
</blockquote>
</div>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
